name: 'JJCommunity '
favicon: null
layout_spectrum: 0.49652
typography_spectrum: 0.5462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#3a3a3c'
    - '#aeafb3'
    - '#b40d3e'
  brandStrength: 1
  lightness: 0.9392949822358787
  saturation: 0.16960077197290957
  rhythmicContrast: 0.41317046131007373
purpose: []
