name: 'JJCommunity '
favicon: null
layout_spectrum: 0.33656
typography_spectrum: 0.54362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#3a3a3c'
    - '#aeafb3'
    - '#b40d3e'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
